# Libraries

In [24]:
import pandas as pd
from sklearn.metrics import mean_squared_error, root_mean_squared_error, mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor

In [2]:
df = pd.read_csv("database\\model_data.csv")
df['FECHA_HORA'] = pd.to_datetime(df['FECHA_HORA'])

In [3]:
df

,FECHA_HORA,IDELEM,INTENSIDAD,OCUPACION,CARGA,VALOR_CONTAMINACION
0,2017-01-01 00:00:00,3910,129.000000,1.000000,3.750000,40.0
1,2017-01-01 00:00:00,3911,151.000000,0.666667,3.666667,40.0
2,2017-01-01 00:00:00,3913,106.750000,0.000000,3.000000,40.0
3,2017-01-01 00:00:00,3914,145.500000,0.250000,3.750000,40.0
4,2017-01-01 00:00:00,3915,118.250000,0.250000,2.750000,40.0
...,...,...,...,...,...,...
464305,2024-12-31 23:00:00,3913,57.333333,0.000000,1.333333,62.0
464306,2024-12-31 23:00:00,3914,56.500000,0.000000,1.250000,62.0
464307,2024-12-31 23:00:00,3915,43.000000,0.000000,0.666667,62.0
464308,2024-12-31 23:00:00,3917,50.000000,0.000000,1.000000,62.0
464309,2024-12-31 23:00:00,5547,70.750000,0.000000,0.500000,62.0

In [4]:
# Me interesa FECHA_HORA para separar en entrenamiento y test
df['HORA'] = df['FECHA_HORA'].dt.hour

In [5]:
df

,FECHA_HORA,IDELEM,INTENSIDAD,OCUPACION,CARGA,VALOR_CONTAMINACION,HORA
0,2017-01-01 00:00:00,3910,129.000000,1.000000,3.750000,40.0,0
1,2017-01-01 00:00:00,3911,151.000000,0.666667,3.666667,40.0,0
2,2017-01-01 00:00:00,3913,106.750000,0.000000,3.000000,40.0,0
3,2017-01-01 00:00:00,3914,145.500000,0.250000,3.750000,40.0,0
4,2017-01-01 00:00:00,3915,118.250000,0.250000,2.750000,40.0,0
...,...,...,...,...,...,...,...
464305,2024-12-31 23:00:00,3913,57.333333,0.000000,1.333333,62.0,23
464306,2024-12-31 23:00:00,3914,56.500000,0.000000,1.250000,62.0,23
464307,2024-12-31 23:00:00,3915,43.000000,0.000000,0.666667,62.0,23
464308,2024-12-31 23:00:00,3917,50.000000,0.000000,1.000000,62.0,23
464309,2024-12-31 23:00:00,5547,70.750000,0.000000,0.500000,62.0,23

In [37]:
train = df[df['FECHA_HORA'] < '2024-01-01']
test = df[df['FECHA_HORA'] >= '2024-01-01']

In [38]:
train = train.groupby(['HORA']).agg({ # train.groupby(['IDELEM','HORA']).agg({
    'INTENSIDAD': 'mean',
    'OCUPACION': 'mean',
    'CARGA': 'mean',
    'VALOR_CONTAMINACION': 'mean'
}).reset_index()

In [39]:
train

    HORA  INTENSIDAD  OCUPACION      CARGA  VALOR_CONTAMINACION
0      0  195.030295   1.168680   7.390287            36.373619
1      1  126.915316   0.740010   4.823568            29.383156
2      2   81.240826   0.434042   2.864462            23.118953
3      3   58.481206   0.331532   1.919874            19.400037
4      4   46.717968   0.306666   1.423832            17.099157
5      5   46.582796   0.268332   1.277559            17.249045
6      6  100.044143   0.489134   2.640945            23.998404
7      7  308.633810   1.723027   9.444120            38.345121
8      8  703.616703   5.863865  26.439154            47.355108
9      9  776.705052   7.049412  31.737022            43.908783
10    10  624.553629   4.766328  25.103575            38.872526
11    11  658.451823   5.057351  25.767263            37.926229
12    12  706.780387   5.520447  27.837836            37.667981
13    13  737.594444   5.563627  28.843171            37.100539
14    14  814.238656   6.008068  31.957317            35.430910
15    15  682.345461   5.096784  27.567715            32.421440
16    16  643.339038   4.715960  25.201099            32.906967
17    17  701.856282   5.550144  27.702727            36.695841
18    18  753.583646   5.994414  29.796298            42.155213
19    19  763.947505   6.184907  30.549160            47.837647
20    20  676.353667   5.075877  26.927319            53.557724
21    21  541.532162   3.850635  21.638476            56.597257
22    22  345.669773   2.384548  13.953236            52.010995
23    23  248.620587   1.594474   9.414312            44.295025

In [40]:
test = test.groupby(['HORA']).agg({ # test.groupby(['IDELEM','HORA']).agg({
    'INTENSIDAD': 'mean',
    'OCUPACION': 'mean',
    'CARGA': 'mean',
    'VALOR_CONTAMINACION': 'mean'
}).reset_index()

In [41]:
test

    HORA  INTENSIDAD  OCUPACION      CARGA  VALOR_CONTAMINACION
0      0  208.321107   1.218308   7.928836            26.643639
1      1  129.887036   0.694062   4.978450            22.535076
2      2   79.656207   0.397119   2.783693            17.732510
3      3   55.694130   0.242284   1.777492            14.949931
4      4   45.044790   0.176152   1.290836            13.054677
5      5   46.735557   0.170134   1.265303            12.931224
6      6   96.355055   0.347432   2.469194            18.136176
7      7  273.028892   1.426012   8.385031            29.321331
8      8  681.223894   6.022458  25.611235            35.002394
9      9  766.348700   8.223201  31.699966            31.497092
10    10  625.209473   4.978369  25.329714            27.870725
11    11  651.100148   4.898455  25.694767            26.953146
12    12  692.428319   5.140484  27.292336            26.756239
13    13  722.083932   5.234274  28.236667            26.227009
14    14  795.727179   5.689687  31.164843            24.903248
15    15  669.261138   4.807688  27.069254            22.529130
16    16  627.588847   4.368386  24.460519            23.201577
17    17  694.216131   5.240392  27.436367            26.534040
18    18  750.069592   5.901443  29.715732            31.667807
19    19  750.529640   6.037563  30.079970            35.852941
20    20  661.975547   4.819254  26.342510            38.287962
21    21  508.799846   3.485636  20.435363            40.292750
22    22  313.010944   1.999858  12.524994            36.474008
23    23  245.823754   1.555337   9.118828            32.536093

In [42]:
features = ['HORA', 'INTENSIDAD', 'OCUPACION', 'CARGA'] # ['IDELEM', 'HORA', 'INTENSIDAD', 'OCUPACION', 'CARGA']
target = ['VALOR_CONTAMINACION']

In [43]:
X_train = train[features]
y_train = train[target]
X_test = test[features]
y_test = test[target]

In [44]:
model = RandomForestRegressor()
model.fit(X_train, y_train)

c:\Users\andre\Documents\Master\TFM\spark_anomaly_detection\.venv\Lib\site-packages\sklearn\base.py:1363: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [45]:
# Save model to pickle
import pickle
with open('database\\models\\pollution_model.pkl', 'wb') as f:
    pickle.dump(model, f)

In [46]:
# Load model
with open('database\\models\\pollution_model.pkl', 'rb') as f:
    model = pickle.load(f)

In [47]:
y_pred = model.predict(X_test)

In [48]:
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")

MSE: 102.00
RMSE: 10.10

In [49]:
mae = mean_absolute_error(y_test, y_pred)
print(f"MAE: {mae:.2f}")

MAE: 9.51

In [50]:
r2 = r2_score(y_test, y_pred)
print(f"R-cuadrado (R²): {r2:.2f}")

R-cuadrado (R²): -0.78

# Repeat process but SCALING the data

In [51]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scale_columns = ['INTENSIDAD', 'OCUPACION', 'CARGA']
train[scale_columns] = scaler.fit_transform(train[scale_columns])
test[scale_columns] = scaler.fit_transform(test[scale_columns])

In [52]:
train

    HORA  INTENSIDAD  OCUPACION     CARGA  VALOR_CONTAMINACION
0      0   -0.987329  -1.028003 -0.966323            36.373619
1      1   -1.229602  -1.211331 -1.191076            29.383156
2      2   -1.392058  -1.342183 -1.362624            23.118953
3      3   -1.473009  -1.386023 -1.445337            19.400037
4      4   -1.514849  -1.396658 -1.488772            17.099157
5      5   -1.515330  -1.413052 -1.501581            17.249045
6      6   -1.325178  -1.318622 -1.382196            23.998404
7      7   -0.583262  -0.790927 -0.786480            38.345121
8      8    0.821620   0.979972  0.701681            47.355108
9      9    1.081582   1.486991  1.165586            43.908783
10    10    0.540407   0.510591  0.584732            38.872526
11    11    0.660976   0.635052  0.642847            37.926229
12    12    0.832872   0.833103  0.824156            37.667981
13    13    0.942472   0.851570  0.912187            37.100539
14    14    1.215082   1.041642  1.184876            35.430910
15    15    0.745962   0.651916  0.800503            32.421440
16    16    0.607223   0.489051  0.593271            32.906967
17    17    0.815358   0.845804  0.812325            36.695841
18    18    0.999343   1.035803  0.995647            42.155213
19    19    1.036205   1.117271  1.061571            47.837647
20    20    0.724650   0.642975  0.744427            53.557724
21    21    0.245115   0.118980  0.281312            56.597257
22    22   -0.451532  -0.508017 -0.391642            52.010995
23    23   -0.796718  -0.845905 -0.789090            44.295025

In [53]:
test

    HORA  INTENSIDAD  OCUPACION     CARGA  VALOR_CONTAMINACION
0      0   -0.916881  -0.933957 -0.895632            26.643639
1      1   -1.200270  -1.152236 -1.156831            22.535076
2      2   -1.381758  -1.275874 -1.351134            17.732510
3      3   -1.468334  -1.340342 -1.440213            14.949931
4      4   -1.506811  -1.367878 -1.483297            13.054677
5      5   -1.500703  -1.370383 -1.485558            12.931224
6      6   -1.321423  -1.296562 -1.378977            18.136176
7      7   -0.683087  -0.847476 -0.855245            29.321331
8      8    0.791754   1.066335  0.669798            35.002394
9      9    1.099317   1.982653  1.208836            31.497092
10    10    0.589370   0.631610  0.644875            27.870725
11    11    0.682915   0.598337  0.677193            26.953146
12    12    0.832237   0.699110  0.818627            26.756239
13    13    0.939385   0.738160  0.902229            26.227009
14    14    1.205464   0.927780  1.161462            24.903248
15    15    0.748532   0.560544  0.798877            22.529130
16    16    0.597967   0.377633  0.567925            23.201577
17    17    0.838696   0.740708  0.831378            26.534040
18    18    1.040499   1.015948  1.033171            31.667807
19    19    1.042161   1.072624  1.065417            35.852941
20    20    0.722208   0.565360  0.734538            38.287962
21    21    0.168772   0.010084  0.211576            40.292750
22    22   -0.538628  -0.608546 -0.488732            36.474008
23    23   -0.781381  -0.793630 -0.790282            32.536093

In [54]:
X_train = train[features]
y_train = train[target]
X_test = test[features]
y_test = test[target]

In [55]:
model_scaled = RandomForestRegressor()
model_scaled.fit(X_train, y_train)

c:\Users\andre\Documents\Master\TFM\spark_anomaly_detection\.venv\Lib\site-packages\sklearn\base.py:1363: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [56]:
with open('database\\models\\pollution_model_scaled.pkl', 'wb') as f:
    pickle.dump(model_scaled, f)

In [57]:
with open('database\\models\\pollution_model_scaled.pkl', 'rb') as f:
    model_scaled = pickle.load(f)

In [58]:
y_pred = model_scaled.predict(X_test)

In [59]:
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")

MSE: 106.92
RMSE: 10.34

In [60]:
mae = mean_absolute_error(y_test, y_pred)
print(f"MAE: {mae:.2f}")

MAE: 9.88

In [61]:
r2 = r2_score(y_test, y_pred)
print(f"R-cuadrado (R²): {r2:.2f}")

R-cuadrado (R²): -0.87

No se si el r2 sirve en regresion, creo que no