# Pollution Data Cleaning

In [1]:
import os
import pandas as pd
from load_transform_service.transform_utils import load_all_csv
import numpy as np

In [3]:
folder = "database\pollution_historical_data_2017_2024"
df = load_all_csv(folder)

In [27]:
df = df.sort_values(by=["ANO", "MES", "DIA"], ascending=True).reset_index(drop=True)

In [21]:
df.head()

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,DIA,H01,V01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,28,79,4,1,28079004_1_38,2017,1,1,7.0,V,...,6.0,V,11.0,V,12.0,V,6.0,V,3.0,V
1,28,79,4,6,28079004_6_48,2017,1,1,0.6,V,...,0.5,V,0.7,V,1.0,V,0.5,V,0.4,V
2,28,79,4,7,28079004_7_8,2017,1,1,83.0,V,...,38.0,V,125.0,V,162.0,V,60.0,V,27.0,V
3,28,79,4,8,28079004_8_8,2017,1,1,45.0,V,...,79.0,V,89.0,V,96.0,V,78.0,V,60.0,V
4,28,79,4,12,28079004_12_8,2017,1,1,172.0,V,...,138.0,V,281.0,V,345.0,V,171.0,V,101.0,V

In [ ]:
#df.to_csv(folder + ".csv", index=False)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354314 entries, 0 to 354313
Data columns (total 56 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PROVINCIA       354314 non-null  int64
 1   MUNICIPIO       354314 non-null  int64
 2   ESTACION        354314 non-null  int64
 3   MAGNITUD        354314 non-null  int64
 4   PUNTO_MUESTREO  354314 non-null  object
 5   ANO             354314 non-null  int64
 6   MES             354314 non-null  int64
 7   DIA             354314 non-null  int64
 8   H01             354314 non-null  float64
 9   V01             354314 non-null  object
 10  H02             354314 non-null  float64
 11  V02             354314 non-null  object
 12  H03             354314 non-null  float64
 13  V03             354314 non-null  object
 14  H04             354314 non-null  float64
 15  V04             354314 non-null  object
 16  H05             354314 non-null  float64
 17  V05             354314 non-null  object
 18  H06             354314 non-null  float64
 19  V06             354314 non-null  object
 20  H07             354314 non-null  float64
 21  V07             354314 non-null  object
 22  H08             354314 non-null  float64
 23  V08             354314 non-null  object
 24  H09             354314 non-null  float64
 25  V09             354314 non-null  object
 26  H10             354314 non-null  float64
 27  V10             354314 non-null  object
 28  H11             354314 non-null  float64
 29  V11             354314 non-null  object
 30  H12             354314 non-null  float64
 31  V12             354314 non-null  object
 32  H13             354314 non-null  float64
 33  V13             354314 non-null  object
 34  H14             354314 non-null  float64
 35  V14             354314 non-null  object
 36  H15             354314 non-null  float64
 37  V15             354314 non-null  object
 38  H16             354314 non-null  float64
 39  V16             354314 non-null  object
 40  H17             354314 non-null  float64
 41  V17             354314 non-null  object
 42  H18             354314 non-null  float64
 43  V18             354314 non-null  object
 44  H19             354314 non-null  float64
 45  V19             354314 non-null  object
 46  H20             354314 non-null  float64
 47  V20             354314 non-null  object
 48  H21             354314 non-null  float64
 49  V21             354314 non-null  object
 50  H22             354314 non-null  float64
 51  V22             354314 non-null  object
 52  H23             354314 non-null  float64
 53  V23             354314 non-null  object
 54  H24             354314 non-null  float64
 55  V24             354314 non-null  object
dtypes: float64(24), int64(7), object(25)
memory usage: 151.4+ MB

In [15]:
df.describe()

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,ANO,MES,DIA,H01,H02,H03,...,H15,H16,H17,H18,H19,H20,H21,H22,H23,H24
count,354314.0,354314.0,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,...,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000
mean,28.0,79.0,35.349509,12.407723,2020.400783,6.523818,15.721792,25.007910,21.554837,18.609889,...,22.045702,21.060994,20.855137,22.291827,25.869837,29.934902,32.916071,34.019786,32.264804,28.667034
std,0.0,0.0,17.987709,8.960133,2.447371,3.448821,8.797602,42.540518,36.055882,30.818417,...,33.756113,42.644517,32.187595,37.704567,125.868275,152.848985,63.163748,63.657605,58.563814,50.521977
min,28.0,79.0,4.000000,1.000000,2017.000000,1.000000,1.000000,-3.000000,-3.000000,-4.000000,...,-7.000000,-3.000000,-60.000000,-42.000000,-14.000000,-17.000000,-28.000000,-7.000000,-3.000000,-2.000000
25%,28.0,79.0,18.000000,7.000000,2018.000000,4.000000,8.000000,1.000000,1.000000,1.000000,...,2.000000,1.530000,1.340000,1.300000,1.360000,1.440000,1.502500,1.570000,1.440000,1.230000
50%,28.0,79.0,38.000000,10.000000,2021.000000,7.000000,16.000000,10.000000,8.000000,7.000000,...,10.000000,9.000000,9.000000,9.000000,10.000000,11.000000,12.000000,13.000000,13.000000,11.000000
75%,28.0,79.0,54.000000,12.000000,2023.000000,10.000000,23.000000,31.000000,27.000000,22.707500,...,27.000000,25.000000,25.000000,27.000000,31.000000,35.000000,39.000000,42.000000,40.000000,35.177500
max,28.0,79.0,60.000000,44.000000,2024.000000,12.000000,31.000000,1865.100000,1869.100000,1875.600000,...,4244.000000,13424.000000,1914.000000,5485.000000,69846.000000,84530.000000,1892.000000,1798.000000,1862.200000,1862.200000

# Filter by station, technique and magnitude

In [26]:
df = pd.read_csv("database\pollution_historical_data_2017_2024.csv", sep=",")
stations = pd.read_csv("database\pollution_stations.csv", sep=",")
magnitudes = pd.read_csv("database\pollution_magnitudes.csv", sep=",")

In [27]:
df.head()

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,DIA,H01,V01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,28,79,4,1,28079004_1_38,2017,1,1,7.0,V,...,6.0,V,11.0,V,12.0,V,6.0,V,3.0,V
1,28,79,4,6,28079004_6_48,2017,1,1,0.6,V,...,0.5,V,0.7,V,1.0,V,0.5,V,0.4,V
2,28,79,4,7,28079004_7_8,2017,1,1,83.0,V,...,38.0,V,125.0,V,162.0,V,60.0,V,27.0,V
3,28,79,4,8,28079004_8_8,2017,1,1,45.0,V,...,79.0,V,89.0,V,96.0,V,78.0,V,60.0,V
4,28,79,4,12,28079004_12_8,2017,1,1,172.0,V,...,138.0,V,281.0,V,345.0,V,171.0,V,101.0,V

In [28]:
# Decompose "PUNTO_MUESTREO" into (station - ESTACION), measurement (magnitude - MAGNITUD) and sampling (technique - TÉCNICA)
df[['ESTACION', 'MAGNITUD', 'TECNICA']] = df['PUNTO_MUESTREO'].str.split("_", expand=True).astype(int)

In [29]:
df.head()

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,DIA,H01,V01,...,V20,H21,V21,H22,V22,H23,V23,H24,V24,TECNICA
0,28,79,28079004,1,28079004_1_38,2017,1,1,7.0,V,...,V,11.0,V,12.0,V,6.0,V,3.0,V,38
1,28,79,28079004,6,28079004_6_48,2017,1,1,0.6,V,...,V,0.7,V,1.0,V,0.5,V,0.4,V,48
2,28,79,28079004,7,28079004_7_8,2017,1,1,83.0,V,...,V,125.0,V,162.0,V,60.0,V,27.0,V,8
3,28,79,28079004,8,28079004_8_8,2017,1,1,45.0,V,...,V,89.0,V,96.0,V,78.0,V,60.0,V,8
4,28,79,28079004,12,28079004_12_8,2017,1,1,172.0,V,...,V,281.0,V,345.0,V,171.0,V,101.0,V,8

In [30]:
df = df.drop(columns=['PROVINCIA', 'MUNICIPIO','PUNTO_MUESTREO'])

In [12]:
df

,ESTACION,MAGNITUD,ANO,MES,DIA,H01,V01,H02,V02,H03,...,V20,H21,V21,H22,V22,H23,V23,H24,V24,TECNICA
0,28079004,1,2017,1,1,7.0,V,6.0,V,6.0,...,V,11.0,V,12.0,V,6.0,V,3.0,V,38
1,28079004,6,2017,1,1,0.6,V,0.6,V,0.5,...,V,0.7,V,1.0,V,0.5,V,0.4,V,48
2,28079004,7,2017,1,1,83.0,V,107.0,V,101.0,...,V,125.0,V,162.0,V,60.0,V,27.0,V,8
3,28079004,8,2017,1,1,45.0,V,56.0,V,54.0,...,V,89.0,V,96.0,V,78.0,V,60.0,V,8
4,28079004,12,2017,1,1,172.0,V,220.0,V,209.0,...,V,281.0,V,345.0,V,171.0,V,101.0,V,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354309,28079060,7,2024,12,31,10.0,V,1.0,V,1.0,...,V,33.0,V,29.0,V,7.0,V,3.0,V,8
354310,28079060,8,2024,12,31,52.0,V,24.0,V,15.0,...,V,77.0,V,68.0,V,47.0,V,36.0,V,8
354311,28079060,10,2024,12,31,15.0,V,6.0,V,5.0,...,V,35.0,V,30.0,V,22.0,V,20.0,V,47
354312,28079060,12,2024,12,31,68.0,V,26.0,V,16.0,...,V,128.0,V,112.0,V,57.0,V,40.0,V,8
354313,28079060,14,2024,12,31,9.0,V,29.0,V,39.0,...,V,4.0,V,3.0,V,16.0,V,21.0,V,6

In [31]:
df.describe()

,ESTACION,MAGNITUD,ANO,MES,DIA,H01,H02,H03,H04,H05,...,H16,H17,H18,H19,H20,H21,H22,H23,H24,TECNICA
count,3.543140e+05,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,...,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000,354314.000000
mean,2.807904e+07,12.407723,2020.400783,6.523818,15.721792,25.007910,21.554837,18.609889,16.716483,15.615701,...,21.060994,20.855137,22.291827,25.869837,29.934902,32.916071,34.019786,32.264804,28.667034,22.819804
std,1.798771e+01,8.960133,2.447371,3.448821,8.797602,42.540518,36.055882,30.818417,27.328815,24.835995,...,42.644517,32.187595,37.704567,125.868275,152.848985,63.163748,63.657605,58.563814,50.521977,20.958651
min,2.807900e+07,1.000000,2017.000000,1.000000,1.000000,-3.000000,-3.000000,-4.000000,-3.000000,-13.000000,...,-3.000000,-60.000000,-42.000000,-14.000000,-17.000000,-28.000000,-7.000000,-3.000000,-2.000000,2.000000
25%,2.807902e+07,7.000000,2018.000000,4.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.530000,1.340000,1.300000,1.360000,1.440000,1.502500,1.570000,1.440000,1.230000,8.000000
50%,2.807904e+07,10.000000,2021.000000,7.000000,16.000000,10.000000,8.000000,7.000000,7.000000,6.000000,...,9.000000,9.000000,9.000000,10.000000,11.000000,12.000000,13.000000,13.000000,11.000000,8.000000
75%,2.807905e+07,12.000000,2023.000000,10.000000,23.000000,31.000000,27.000000,22.707500,20.000000,19.000000,...,25.000000,25.000000,27.000000,31.000000,35.000000,39.000000,42.000000,40.000000,35.177500,47.000000
max,2.807906e+07,44.000000,2024.000000,12.000000,31.000000,1865.100000,1869.100000,1875.600000,1876.700000,1878.500000,...,13424.000000,1914.000000,5485.000000,69846.000000,84530.000000,1892.000000,1798.000000,1862.200000,1862.200000,59.000000

In [46]:
df_station = df[df['ESTACION'] == 28079011].reset_index(drop=True)

In [47]:
df_station.head(20)

,ESTACION,MAGNITUD,ANO,MES,DIA,H01,V01,H02,V02,H03,...,V20,H21,V21,H22,V22,H23,V23,H24,V24,TECNICA
0,28079011,7,2017,1,1,10.0,V,22.0,V,21.0,...,V,85.0,V,73.0,V,29.0,V,11.0,V,8
1,28079011,8,2017,1,1,40.0,V,44.0,V,46.0,...,V,87.0,V,81.0,V,66.0,V,45.0,V,8
2,28079011,12,2017,1,1,56.0,V,78.0,V,77.0,...,V,218.0,V,193.0,V,109.0,V,62.0,V,8
3,28079011,20,2017,1,1,3.4,V,3.6,V,4.0,...,V,4.3,V,5.2,V,4.1,V,3.8,V,59
4,28079011,30,2017,1,1,2.8,V,3.0,V,2.9,...,V,2.9,V,3.2,V,2.6,V,2.2,V,59
5,28079011,35,2017,1,1,0.1,V,0.1,V,0.1,...,V,0.2,V,0.4,V,0.2,V,0.2,V,59
6,28079011,7,2017,1,2,3.0,V,1.0,V,2.0,...,V,35.0,V,49.0,V,34.0,V,10.0,V,8
7,28079011,8,2017,1,2,28.0,V,21.0,V,20.0,...,V,76.0,V,80.0,V,75.0,V,54.0,V,8
8,28079011,12,2017,1,2,33.0,V,24.0,V,22.0,...,V,130.0,V,154.0,V,127.0,V,69.0,V,8
9,28079011,20,2017,1,2,5.1,V,1.3,V,1.5,...,V,4.6,V,4.9,V,5.0,V,4.3,V,59
10,28079011,30,2017,1,2,2.4,V,1.5,V,1.8,...,V,2.5,V,2.7,V,3.0,V,2.9,V,59
11,28079011,35,2017,1,2,0.2,V,0.1,V,0.1,...,V,0.3,V,0.3,V,0.3,V,0.1,V,59
12,28079011,7,2017,1,3,7.0,V,3.0,V,3.0,...,V,93.0,V,171.0,V,105.0,V,210.0,V,8
13,28079011,8,2017,1,3,48.0,V,42.0,V,35.0,...,V,86.0,V,105.0,V,83.0,V,110.0,V,8
14,28079011,12,2017,1,3,58.0,V,47.0,V,40.0,...,V,230.0,V,368.0,V,244.0,V,432.0,V,8
15,28079011,20,2017,1,3,3.1,V,3.2,V,2.8,...,V,7.7,V,10.3,V,9.1,V,10.1,V,59
16,28079011,30,2017,1,3,2.4,V,2.3,V,2.1,...,V,3.5,V,4.2,V,3.7,V,4.3,V,59
17,28079011,35,2017,1,3,0.2,V,0.2,V,0.1,...,V,1.0,V,2.3,V,2.9,V,1.9,V,59
18,28079011,7,2017,1,4,241.0,V,242.0,V,143.0,...,V,110.0,V,107.0,V,139.0,V,147.0,V,8
19,28079011,8,2017,1,4,117.0,V,112.0,V,81.0,...,V,88.0,V,81.0,V,84.0,V,86.0,V,8

In [42]:
stations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CODIGO         38 non-null     int64
 1   NOMBRE         38 non-null     object
 2   SITUACION      38 non-null     object
 3   OBSERVACIONES  30 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.3+ KB

# Join to get station name

In [48]:
df_station = df_station.merge(stations, left_on="ESTACION", right_on="CODIGO", how="left")
df_station

,ESTACION,MAGNITUD,ANO,MES,DIA,H01,V01,H02,V02,H03,...,V22,H23,V23,H24,V24,TECNICA,CODIGO,NOMBRE,SITUACION,OBSERVACIONES
0,28079011,7,2017,1,1,10.0,V,22.0,V,21.0,...,V,29.0,V,11.0,V,8,28079011,Av. Ramón y Cajal,Alta,NaN
1,28079011,8,2017,1,1,40.0,V,44.0,V,46.0,...,V,66.0,V,45.0,V,8,28079011,Av. Ramón y Cajal,Alta,NaN
2,28079011,12,2017,1,1,56.0,V,78.0,V,77.0,...,V,109.0,V,62.0,V,8,28079011,Av. Ramón y Cajal,Alta,NaN
3,28079011,20,2017,1,1,3.4,V,3.6,V,4.0,...,V,4.1,V,3.8,V,59,28079011,Av. Ramón y Cajal,Alta,NaN
4,28079011,30,2017,1,1,2.8,V,3.0,V,2.9,...,V,2.6,V,2.2,V,59,28079011,Av. Ramón y Cajal,Alta,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14932,28079011,8,2024,12,31,28.0,V,20.0,V,16.0,...,V,56.0,V,62.0,V,8,28079011,Av. Ramón y Cajal,Alta,NaN
14933,28079011,12,2024,12,31,30.0,V,21.0,V,17.0,...,V,63.0,V,67.0,V,8,28079011,Av. Ramón y Cajal,Alta,NaN
14934,28079011,20,2024,12,31,1.9,V,0.5,V,0.5,...,V,1.9,V,1.6,V,59,28079011,Av. Ramón y Cajal,Alta,NaN
14935,28079011,30,2024,12,31,0.6,V,0.3,V,0.2,...,V,0.8,V,0.9,V,59,28079011,Av. Ramón y Cajal,Alta,NaN
14936,28079011,35,2024,12,31,0.2,V,0.1,V,0.1,...,V,0.2,V,0.1,V,59,28079011,Av. Ramón y Cajal,Alta,NaN

In [50]:
df_station = df_station.drop(columns=["ESTACION", "SITUACION", "OBSERVACIONES"]).reset_index(drop=True)

In [51]:
df_total = df_station[df_station["MAGNITUD"] == 8] # and tecnica = 8

In [52]:
df_total

,MAGNITUD,ANO,MES,DIA,H01,V01,H02,V02,H03,V03,...,V21,H22,V22,H23,V23,H24,V24,TECNICA,CODIGO,NOMBRE
1,8,2017,1,1,40.0,V,44.0,V,46.0,V,...,V,81.0,V,66.0,V,45.0,V,8,28079011,Av. Ramón y Cajal
7,8,2017,1,2,28.0,V,21.0,V,20.0,V,...,V,80.0,V,75.0,V,54.0,V,8,28079011,Av. Ramón y Cajal
13,8,2017,1,3,48.0,V,42.0,V,35.0,V,...,V,105.0,V,83.0,V,110.0,V,8,28079011,Av. Ramón y Cajal
19,8,2017,1,4,117.0,V,112.0,V,81.0,V,...,V,81.0,V,84.0,V,86.0,V,8,28079011,Av. Ramón y Cajal
25,8,2017,1,5,82.0,V,62.0,V,57.0,V,...,V,136.0,V,107.0,V,80.0,V,8,28079011,Av. Ramón y Cajal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14908,8,2024,12,27,66.0,V,48.0,V,48.0,V,...,V,53.0,V,49.0,V,55.0,V,8,28079011,Av. Ramón y Cajal
14914,8,2024,12,28,46.0,V,31.0,V,19.0,V,...,V,112.0,V,101.0,V,92.0,V,8,28079011,Av. Ramón y Cajal
14920,8,2024,12,29,53.0,V,15.0,V,9.0,V,...,V,90.0,V,63.0,V,37.0,V,8,28079011,Av. Ramón y Cajal
14926,8,2024,12,30,29.0,V,24.0,V,14.0,V,...,V,85.0,V,83.0,V,76.0,V,8,28079011,Av. Ramón y Cajal
14932,8,2024,12,31,28.0,V,20.0,V,16.0,V,...,V,76.0,V,56.0,V,62.0,V,8,28079011,Av. Ramón y Cajal

In [ ]:
# fila = df_total[(df_total["ANO"] == 2019) & (df_total["MES"] == 1) & (df_total["DIA"] == 1)]
# fila

# Join to get the technique and magnitude name

In [53]:
magnitudes

,COD_MAGNITUD,NOMBRE,ABREVIATURA,UNIDAD,COD_TECNICA,TECNICA_MEDIDA
0,1,Dióxido de Azufre,SO2,µg/m3,38,Fluorescencia ultravioleta
1,6,Monóxido de Carbono,CO,mg/m3,48,Absorción infrarroja
2,7,Monóxido de Nitrógeno,NO,µg/m3,8,Quimioluminiscencia
3,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
4,9,Partículas < 2.5 µm,PM2.5,µg/m3,47,Microbalanza/Espectrometría
5,10,Partículas < 10 µm,PM10,µg/m3,47,Microbalanza/Espectrometría
6,12,Óxidos de Nitrógeno,NOx,µg/m3,8,Quimioluminiscencia
7,14,Ozono,O3,µg/m3,6,Absorción ultravioleta
8,20,Tolueno,TOL,µg/m3,59,Cromatografía de gases
9,30,Benceno,BEN,µg/m3,59,Cromatografía de gases
10,35,Etilbenceno,EBE,µg/m3,59,Cromatografía de gases
11,37,Metaxileno,MXY,µg/m3,59,Cromatografía de gases
12,38,Paraxileno,PXY,µg/m3,59,Cromatografía de gases
13,39,Ortoxileno,OXY,µg/m3,59,Cromatografía de gases
14,42,Hidrocarburos totales (hexano),TCH,mg/m3,59,Cromatografía de gases
15,43,Metano,CH4,mg/m3,59,Cromatografía de gases
16,44,Hidrocarburos no metánicos (hexano),NMHC,mg/m3,59,Cromatografía de gases
17,431,Metaparaxileno,MPX,mg/m3,59,Cromatografía de gases

In [57]:
magnitudes = magnitudes.rename(columns={'NOMBRE': 'NOMBRE_MAGNITUD'})

In [59]:
df_total = df_total.merge(magnitudes, left_on=["MAGNITUD", "TECNICA"], right_on=["COD_MAGNITUD", "COD_TECNICA"], how="left")

In [60]:
df_total

,MAGNITUD,ANO,MES,DIA,H01,V01,H02,V02,H03,V03,...,V24,TECNICA,CODIGO,NOMBRE,COD_MAGNITUD,NOMBRE_MAGNITUD,ABREVIATURA,UNIDAD,COD_TECNICA,TECNICA_MEDIDA
0,8,2017,1,1,40.0,V,44.0,V,46.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
1,8,2017,1,2,28.0,V,21.0,V,20.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
2,8,2017,1,3,48.0,V,42.0,V,35.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
3,8,2017,1,4,117.0,V,112.0,V,81.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
4,8,2017,1,5,82.0,V,62.0,V,57.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,8,2024,12,27,66.0,V,48.0,V,48.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
2496,8,2024,12,28,46.0,V,31.0,V,19.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
2497,8,2024,12,29,53.0,V,15.0,V,9.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
2498,8,2024,12,30,29.0,V,24.0,V,14.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
2499,8,2024,12,31,28.0,V,20.0,V,16.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia

In [61]:
df_total.drop(columns=["COD_MAGNITUD", "COD_TECNICA"]).reset_index(drop=True)

,MAGNITUD,ANO,MES,DIA,H01,V01,H02,V02,H03,V03,...,V23,H24,V24,TECNICA,CODIGO,NOMBRE,NOMBRE_MAGNITUD,ABREVIATURA,UNIDAD,TECNICA_MEDIDA
0,8,2017,1,1,40.0,V,44.0,V,46.0,V,...,V,45.0,V,8,28079011,Av. Ramón y Cajal,Dióxido de Nitrógeno,NO2,µg/m3,Quimioluminiscencia
1,8,2017,1,2,28.0,V,21.0,V,20.0,V,...,V,54.0,V,8,28079011,Av. Ramón y Cajal,Dióxido de Nitrógeno,NO2,µg/m3,Quimioluminiscencia
2,8,2017,1,3,48.0,V,42.0,V,35.0,V,...,V,110.0,V,8,28079011,Av. Ramón y Cajal,Dióxido de Nitrógeno,NO2,µg/m3,Quimioluminiscencia
3,8,2017,1,4,117.0,V,112.0,V,81.0,V,...,V,86.0,V,8,28079011,Av. Ramón y Cajal,Dióxido de Nitrógeno,NO2,µg/m3,Quimioluminiscencia
4,8,2017,1,5,82.0,V,62.0,V,57.0,V,...,V,80.0,V,8,28079011,Av. Ramón y Cajal,Dióxido de Nitrógeno,NO2,µg/m3,Quimioluminiscencia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,8,2024,12,27,66.0,V,48.0,V,48.0,V,...,V,55.0,V,8,28079011,Av. Ramón y Cajal,Dióxido de Nitrógeno,NO2,µg/m3,Quimioluminiscencia
2496,8,2024,12,28,46.0,V,31.0,V,19.0,V,...,V,92.0,V,8,28079011,Av. Ramón y Cajal,Dióxido de Nitrógeno,NO2,µg/m3,Quimioluminiscencia
2497,8,2024,12,29,53.0,V,15.0,V,9.0,V,...,V,37.0,V,8,28079011,Av. Ramón y Cajal,Dióxido de Nitrógeno,NO2,µg/m3,Quimioluminiscencia
2498,8,2024,12,30,29.0,V,24.0,V,14.0,V,...,V,76.0,V,8,28079011,Av. Ramón y Cajal,Dióxido de Nitrógeno,NO2,µg/m3,Quimioluminiscencia
2499,8,2024,12,31,28.0,V,20.0,V,16.0,V,...,V,62.0,V,8,28079011,Av. Ramón y Cajal,Dióxido de Nitrógeno,NO2,µg/m3,Quimioluminiscencia

In [3]:
# df_total.to_csv("database\\pollution_final" + ".csv", index=False)
df = pd.read_csv("database\\pollution_final.csv")

In [6]:
df.describe()

,MAGNITUD,ANO,MES,DIA,H01,H02,H03,H04,H05,H06,...,H19,H20,H21,H22,H23,H24,TECNICA,CODIGO,COD_MAGNITUD,COD_TECNICA
count,2500.0,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,...,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.0,2500.0,2500.0,2500.0
mean,8.0,2020.518400,6.632000,15.726800,35.218000,28.546800,22.450800,18.916800,16.625600,16.736800,...,40.895600,46.576400,51.965600,54.774800,50.170000,42.954000,8.0,28079011.0,8.0,8.0
std,0.0,2.441812,3.409226,8.803952,31.508811,26.484312,22.585598,19.575249,16.939168,15.363188,...,30.317103,36.845135,42.190317,42.708398,41.512042,37.395145,0.0,0.0,0.0,0.0
min,8.0,2017.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.0,28079011.0,8.0,8.0
25%,8.0,2018.000000,4.000000,8.000000,12.000000,9.000000,7.000000,6.000000,6.000000,7.000000,...,20.000000,21.000000,22.750000,24.000000,19.000000,16.000000,8.0,28079011.0,8.0,8.0
50%,8.0,2021.000000,7.000000,16.000000,23.000000,18.000000,13.000000,11.000000,10.000000,11.000000,...,32.000000,35.000000,39.000000,41.000000,34.000000,28.000000,8.0,28079011.0,8.0,8.0
75%,8.0,2023.000000,10.000000,23.000000,49.000000,38.000000,29.000000,23.000000,20.000000,21.000000,...,53.000000,61.000000,69.000000,75.000000,71.000000,60.000000,8.0,28079011.0,8.0,8.0
max,8.0,2024.000000,12.000000,31.000000,192.000000,151.000000,147.000000,142.000000,126.000000,120.000000,...,237.000000,311.000000,331.000000,289.000000,251.000000,240.000000,8.0,28079011.0,8.0,8.0

In [18]:
df

,MAGNITUD,ANO,MES,DIA,H01,V01,H02,V02,H03,V03,...,V24,TECNICA,CODIGO,NOMBRE,COD_MAGNITUD,NOMBRE_MAGNITUD,ABREVIATURA,UNIDAD,COD_TECNICA,TECNICA_MEDIDA
0,8,2017,1,1,40.0,V,44.0,V,46.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
1,8,2017,1,2,28.0,V,21.0,V,20.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
2,8,2017,1,3,48.0,V,42.0,V,35.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
3,8,2017,1,4,117.0,V,112.0,V,81.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
4,8,2017,1,5,82.0,V,62.0,V,57.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,8,2024,12,27,66.0,V,48.0,V,48.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
2496,8,2024,12,28,46.0,V,31.0,V,19.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
2497,8,2024,12,29,53.0,V,15.0,V,9.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
2498,8,2024,12,30,29.0,V,24.0,V,14.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia
2499,8,2024,12,31,28.0,V,20.0,V,16.0,V,...,V,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia

# Standarize date to later join with traffic

In [ ]:
# Create a list with hourly columns (H01 a H24)
horas = [f'H{str(i).zfill(2)}' for i in range(1, 25)]
horas

In [ ]:
df_largo = df.melt(
    id_vars=['ANO', 'MES', 'DIA', 'MAGNITUD', 'TECNICA', 'CODIGO', 'NOMBRE', 'COD_MAGNITUD', 'NOMBRE_MAGNITUD', 'ABREVIATURA', 'UNIDAD', 'COD_TECNICA', 'TECNICA_MEDIDA'],
    value_vars=horas,
    var_name='HORA',
    value_name='VALOR_CONTAMINACION'
)
df_largo

,ANO,MES,DIA,MAGNITUD,TECNICA,CODIGO,NOMBRE,COD_MAGNITUD,NOMBRE_MAGNITUD,ABREVIATURA,UNIDAD,COD_TECNICA,TECNICA_MEDIDA,HORA,VALOR_CONTAMINACION
0,2017,1,1,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,H01,40.0
1,2017,1,2,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,H01,28.0
2,2017,1,3,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,H01,48.0
3,2017,1,4,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,H01,117.0
4,2017,1,5,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,H01,82.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,2024,12,27,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,H24,55.0
59996,2024,12,28,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,H24,92.0
59997,2024,12,29,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,H24,37.0
59998,2024,12,30,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,H24,76.0
59999,2024,12,31,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,H24,62.0

In [ ]:
df_largo['HORA'] = df_largo['HORA'].str.extract('H(\d+)').astype(int) - 1  # 0-23
# df_largo['FECHA_HORA'] = pd.to_datetime(df_largo[['ANO', 'MES', 'DIA']]) + pd.to_timedelta(df_largo['HORA'], unit='h')
df_largo['FECHA_HORA'] = pd.to_datetime(
    dict(year=df_largo['ANO'], month=df_largo['MES'], day=df_largo['DIA'])
) + pd.to_timedelta(df_largo['HORA'], unit='h')

In [ ]:
df_largo = df_largo.sort_values(by='FECHA_HORA').reset_index(drop=True)
df_largo

,ANO,MES,DIA,MAGNITUD,TECNICA,CODIGO,NOMBRE,COD_MAGNITUD,NOMBRE_MAGNITUD,ABREVIATURA,UNIDAD,COD_TECNICA,TECNICA_MEDIDA,HORA,VALOR_CONTAMINACION,FECHA_HORA
0,2017,1,1,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,0,40.0,2017-01-01 00:00:00
1,2017,1,1,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,1,44.0,2017-01-01 01:00:00
2,2017,1,1,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,2,46.0,2017-01-01 02:00:00
3,2017,1,1,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,3,43.0,2017-01-01 03:00:00
4,2017,1,1,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,4,33.0,2017-01-01 04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,2024,12,31,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,19,85.0,2024-12-31 19:00:00
59996,2024,12,31,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,20,85.0,2024-12-31 20:00:00
59997,2024,12,31,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,21,76.0,2024-12-31 21:00:00
59998,2024,12,31,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,22,56.0,2024-12-31 22:00:00
59999,2024,12,31,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,23,62.0,2024-12-31 23:00:00

In [ ]:
df_largo = df_largo.dropna(subset=['VALOR_CONTAMINACION'])
df_largo

# print(df_largo[['FECHA_HORA', 'VALOR_CONTAMINACION']].head())

,ANO,MES,DIA,MAGNITUD,TECNICA,CODIGO,NOMBRE,COD_MAGNITUD,NOMBRE_MAGNITUD,ABREVIATURA,UNIDAD,COD_TECNICA,TECNICA_MEDIDA,HORA,VALOR_CONTAMINACION,FECHA_HORA
0,2017,1,1,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,0,40.0,2017-01-01 00:00:00
1,2017,1,1,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,1,44.0,2017-01-01 01:00:00
2,2017,1,1,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,2,46.0,2017-01-01 02:00:00
3,2017,1,1,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,3,43.0,2017-01-01 03:00:00
4,2017,1,1,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,4,33.0,2017-01-01 04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,2024,12,31,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,19,85.0,2024-12-31 19:00:00
59996,2024,12,31,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,20,85.0,2024-12-31 20:00:00
59997,2024,12,31,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,21,76.0,2024-12-31 21:00:00
59998,2024,12,31,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,22,56.0,2024-12-31 22:00:00
59999,2024,12,31,8,8,28079011,Av. Ramón y Cajal,8,Dióxido de Nitrógeno,NO2,µg/m3,8,Quimioluminiscencia,23,62.0,2024-12-31 23:00:00

In [27]:
df_largo = df_largo.drop(columns=['ANO', 'MES', 'DIA', 'HORA']).reset_index(drop=True)

In [ ]:
# df_largo.to_csv("database\\pollution_date_value" + ".csv", index=False)

# Conclusion

We need just the date and the value to join to the traffic dataframe